---
booktitle: 'Proceedings of Workshop on Causality: Objectives and Assessment at NIPS
  2008'
series: Proceedings of Machine Learning Research
issn: 1938-7228
volume: 6
year: '2008'
start: 2008-12-12
end: 2008-12-12
published: 2010-02-18
shortname: COA
bibsource: http://jmlr.csail.mit.edu/proceedings/
sections:
- name: intro
  title: Introduction
- name: theory
  title: Fundamentals and Algorithms
- name: challenge
  title: Challenge Contributions
layout: proceedings
id: GuyonIJDSB2008
month: 0
cycles: false
editor:
- given: Isabelle
  family: Guyon
- given: Dominik
  family: Janzing
- given: Bernhard
  family: Schölkopf
title: Proceedings of Machine Learning Research
description: |
  Proceedings of Workshop on Causality: Objectives and Assessment at NIPS 2008
    Held in Whistler, Canada on 12 December 2008

  Published as Volume 6 by the Proceedings of Machine Learning Research on 18 February 2010.

  Volume Edited by:
    Isabelle Guyon
    Dominik Janzing
    Bernhard Schölkopf

  Series Editors:
    Neil D. Lawrence
date_str: 12 Dec
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v6"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v6
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: 'Causality: Objectives and Assessment'
  url: 
  location: Whistler, Canada
  dates:
  - 2008-12-12
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
