---
booktitle: 'Proceedings of Workshop on Causality: Objectives and Assessment at NIPS
  2008'
series: Proceedings of Machine Learning Research
volume: 6
year: '2008'
start: 2008-12-12
end: 2008-12-12
published: 2010-02-18
shortname: COA
bibsource: http://jmlr.csail.mit.edu/proceedings/
sections:
- name: intro
  title: Introduction
- name: theory
  title: Fundamentals and Algorithms
- name: challenge
  title: Challenge Contributions
layout: proceedings
id: GuyonIJDSB2008
month: 0
abstract: ''
editor:
- given: Isabelle
  family: Guyon
- given: Dominik
  family: Janzing
- given: Bernhard
  family: Schölkopf
title: 'Proceedings of Workshop on Causality: Objectives and Assessment at NIPS 2008'
email: ''
description: 'Proceedings of Workshop on Causality: Objectives and Assessment at NIPS
  2008'
url: http://proceedings.mlr.press
baseurl: "/v6"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v6
conference:
  name: 'Causality: Objectives and Assessment'
  url: 
  location: 
  dates:
  - 2008-12-12
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v6.bib
